### PR TITLE
Avoid possible crash with btree merging ( issue #84 )

### PR DESCRIPTION
**Pull request by harukat**
Although PostgreSQL tuplesort API tuplesort_getindextuple doesn't ensure
the data returned after next call, pg_bulkload btree merging code would
refer such data. Hence CopyIndexTuple is added before getting next item.

Additionally, BTReaderInit in merging could fail, therefore now pg_bulkload do
reindex rather than index merging in such a case.

The crash is reported in the following issues:
https://github.com/ossc-db/pg_bulkload/issues/84
https://github.com/ossc-db/pg_bulkload/issues/85

### CODE REVIEW

**Comment by MoonInsung** [comment]
Dear Haruka Takatsuka-san.
Thank you for sent PR.
I was not able to check PR properly due to other work.
I'll check the PR contents sent from the coming May.
I apologize for the inconvenience and slow checked.

Best regards.

**Comment by harukat** [comment]
> I'll check the PR contents sent from the coming May.

Thanks for your comments.
How has the check progressed since then?
Can I expect this problem will be fix by my way or other ways?

**Comment by MoonInsung** [comment]
> > I'll check the PR contents sent from the coming May.
> 
> Thanks for your comments.
> How has the check progressed since then?
> Can I expect this problem will be fix by my way or other ways?

Dear Haruka Takatsuka-san.

We are currently review status.
The issue you report may be a critical problme one, so I'll check it a little carefully.
Maybe, We will probably fix it based on This PR.
Probably the fix is ​​expected at the end of May or in early June.

Best regards.
Moon.

**Comment by nobleread** [comment]
end of May early June has passed may we have an update?

**Comment by nobleread** [comment]
Any news on progress? Thanks!

**Comment by harukat** [comment]
Any news on progress?
Is there anything that I can help with?
Thanks.

**Comment by MoonInsung** [comment]
I apologize for the late response.
We will apply your patch and plan to release it to build against PG13 with a new compatible version soon.
The estimated target date is during September. But late again, I will comment in advance.
Best regards.

**Comment by MoonInsung** [comment]
I'm sorry for responding too late.
We have finally started the PG13 response work and have reviewed the PR you sent us.
I checked the motion of this PR and agreed with your opinion. 
Once again, I'm sorry for responding too late.

Best regards.

**Pull request merged**
