### PR TITLE
Fixed broken library paths on ubuntu packages(#97)

### LINKED ISSUE #97: Problems in build 3.1.16 using Postgres 11 using the postgres Docker Debian
Hi,

I having trouble trying to build pg_bulkload (https://github.com/ossc-db/pg_bulkload/tree/VERSION3_1_16) in postgres Docker Debian (https://hub.docker.com/_/postgres).

Then I write:
apt-get install build-essential postgresql-server-dev-11 postgresql-contrib-11 libpam-dev libssl-dev libreadline-dev libselinux-dev libedit-dev

But show the following errors that I don't know how need to fix or find other libraries:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer pg_bulkload.o recovery.o pgut/pgut.o pgut/pgut-fe.o pgut/pgut-list.o  -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed -Wl,--build-id  -L/usr/lib/x86_64-linux-gnu -lpq -lpgcommon -lpgport -lpthread -lselinux -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm -o pg_bulkload
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk:430: recipe for target 'pg_bulkload' failed
```

How find pgcommon or pgport to install?

Regards,
Cesar Jorge

### PR DESCRIPTION
**Pull request by mikecaat**
This patch fix #97. I tested this patch works with the following dockerfile.

``` 
> cat Dockerfile
FROM postgres:11
RUN apt-get update && \
  apt-get install -y \
    git \
    build-essential \
    libpam-dev \
    libssl-dev \
    libreadline-dev \
    libselinux-dev \
    libedit-dev \
    libkrb5-dev \
    zlib1g-dev \
    postgresql-server-dev-11 \
    postgresql-contrib-11
COPY pg_bulkload /pg_bulkload
RUN cd /pg_bulkload && make && make install
CMD ["pg_bulkload", "--version"]
```

This patch refers to pg_repack project's [issue](https://github.com/reorg/pg_repack/issues/179) and [PR](https://github.com/reorg/pg_repack/commit/58e8e60c41b41072d6118237a7d0a2cf7c772af7)

### CODE REVIEW

**Comment by mikecaat** [comment]
This patch needs to be merged to the master branch.
I tested with the following dockerfile and pg_bulkload's master branch.

```
> cat Dockerfile
FROM postgres:13
RUN apt-get update && \
  apt-get install -y \
    git \
    build-essential \
    libpam-dev \
    libssl-dev \
    libreadline-dev \
    libselinux-dev \
    libedit-dev \
    libkrb5-dev \
    zlib1g-dev \
    postgresql-server-dev-13 \
    postgresql-contrib-13
COPY pg_bulkload /pg_bulkload
RUN cd /pg_bulkload && make && make install
CMD ["pg_bulkload", "--version"]
```

**Comment by MoonInsung** [comment]
Dear mikecaat.

Thank you for responding to the issue.
Unfortunately, I'm not using the Debian OS, so I can't check it directly.
If there was no problem in your environment, please commit yourself.
Or is it better to commit after I try to test after setup the Ubuntu environment next Monday?

Best regards.
Moon.

**Comment by mikecaat** [comment]
Dear @MoonInsung 

Thanks for responding. I added the workflow(.github/workflows/build.yml) to check if the building is successful on Ubuntu OS. Is it enough?

**Comment by mikecaat** [comment]
We don't need merging this patch to "ossc-db:REL_UNDER_PG13_STABLE" because the branch is already deprecated. So, close this PR.

**Pull request closed without merging**
