### PR TITLE
merge pgut-list.c

### PR DESCRIPTION
**Pull request by yanmeisun**
In version 3.1.17, it was separated into 2 branches since using different pgut-list.c in different postgresql version. It takes a little trouble while using the tool. Merge pgut-list.c to slove this problem.

### CODE REVIEW

**Comment by mikecaat** [comment]
Hi, @yanmeisun 

Thanks for your works!

I think it's better to modify the workflow for testing. Now, the test is executed with only PostgreSQL version 13 because the master branch doesn't support another version without your patches. You can see the test result on [this](https://github.com/ossc-db/pg_bulkload/pull/102/checks).

(Although there is a possibility that other problems may happen...)
Since we can test with another version to comment in from L20 to L27 in this [file](https://github.com/ossc-db/pg_bulkload/blob/master/.github/workflows/build.yml#L20), is it better to do so?

**Comment by mikecaat** [comment]
Hi, 

Thanks for updating!

"make installcheck" with 9.6.21 seems to be failed.

Although "show the result if the regression test failed" in [the build result](https://github.com/ossc-db/pg_bulkload/pull/102/checks?check_run_id=2581576197)  should show the reason, it is broken.
This is my fault, sorry. I think you need to change the following source codes.

```
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -138,5 +138,5 @@ jobs:
       if: failure()
       shell: bash -xe {0}
       run: |
-        cat regression.diffs   \
+        cat bin/regression.diffs   \
          && exit 1     # notify fail
```

**Comment by yanmeisun** [comment]
Hi @mikecaat 
Thanks for your comments. Since I'm not sure where is the problem, I fixed ​the code to show regression.diffs which may be helpful to find out the problem.

**Comment by yanmeisun** [comment]
Hi,
It seem that there is a mistake in <expected/write_bin_1.out> which makes the regression test failed in all PostgreSQL version except PG 13.
Fixed this mistake to let the regression test pass correctly in PostgreSQL version under 13.

**Comment by MoonInsung** [comment]
Dear @yanmeisun .

Thank you for responding to this issue.

As for your suggestion that all branches can use pgut-list.c, I think it LGTM.
Therefore, I will commit the patch.

However, the current regression test remains a problem.
The reason is as follows.

- For PG11 or lower version, refer to write_bin.out
- For PG12 version, refer to write_bin_1.out
- For PG13 or higher version, refer to write_bin_2.out

However, when I committed the previous #93 regression test, 
I mistakenly recognized that there was no problem with the modified file, so I committed it.
Due to this mistake, the current PG12 failed the regression test.

Therefore, First, committing the patch you sent this PR, 
I will modify the regression test file without PR.

Best regards.
Moon.

**Comment by MoonInsung** [comment]
I will commit it around 13:00 JST on May 21.
After that, I will commit the modifications related to the regression test.

**Comment by MoonInsung** [comment]
Modification related to regression test has been committed.(466be03)

**Pull request merged**
